# Generated by Django 3.0.8 on 2020-07-27 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('deco', models.CharField(max_length=200)),
                ('icon1', models.CharField(max_length=50)),
                ('icon2', models.CharField(max_length=50)),
                ('desc1', models.CharField(max_length=200)),
                ('desc2', models.CharField(max_length=200)),
                ('desc3', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('pricenum', models.IntegerField(null=True)),
                ('colors', models.CharField(max_length=50, null=True)),
                ('image_product', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Product_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon1', models.CharField(max_length=50)),
                ('icon2', models.CharField(max_length=50)),
                ('explanation', models.TextField()),
                ('period', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('image_detail', models.CharField(max_length=100)),
                ('rest', models.TextField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product')),
            ],
            options={
                'db_table': 'product_details',
            },
        ),
    ]
