# Generated by Django 3.0.8 on 2020-09-19 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='deco',
            new_name='decoration',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='desc1',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='desc2',
            new_name='description2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='desc3',
            new_name='description3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pricenum',
            new_name='price_number',
        ),
    ]
