# Generated by Django 3.0.8 on 2020-09-19 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20200727_1123'),
        ('product', '0002_auto_20200919_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('post_number', models.CharField(max_length=10, null=True)),
                ('address_street', models.CharField(max_length=200)),
                ('address_detail', models.CharField(max_length=200)),
                ('customer_request', models.TextField()),
                ('points', models.IntegerField()),
                ('card_number', models.CharField(max_length=30)),
                ('expired_month', models.IntegerField()),
                ('expired_year', models.IntegerField()),
                ('birth', models.IntegerField()),
                ('card_kakao', models.CharField(max_length=20, null=True)),
                ('card_password', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('purchased_item', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('count', models.CharField(max_length=100, null=True)),
                ('total_price', models.CharField(max_length=100, null=True)),
                ('back_image', models.CharField(max_length=200, null=True)),
                ('pill_image', models.CharField(max_length=200, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
