# Generated by Django 3.0.8 on 2020-07-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='userquestion',
            new_name='user_question',
        ),
    ]
