# Generated by Django 3.0.8 on 2020-07-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200730_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='sub_quesion',
            new_name='sub_question',
        ),
    ]
